package com.fingerprintjs.android.fpjs_pro_demo.ui.screens.drn.component

import androidx.compose.runtime.Composable


enum class Country(
    val code: String,
    val index: Int
) {
    ALGERIA(code = "DZ", index = 0),
    AFGHANISTAN(code = "AF", index = 1),
    ALBANIA(code = "AL", index = 2),
    ANDORRA(code = "AD", index = 3),
    ANGOLA(code = "AO", index = 4),
    ANTIGUA_AND_BARBUDA(code = "AG", index = 5),
    AUSTRALIA(code = "AU", index = 6),
    ARGENTINA(code = "AR", index = 7),
    ARMENIA(code = "AM", index = 8),
    ARUBA(code = "AW", index = 9),
    // EUROPE(countryCode = "", index = -1), // Not a country
    AUSTRIA(code = "AT", index = 11),
    AZERBAIJAN(code = "AZ", index = 12),
    BAHAMAS(code = "BS", index = 13),
    BAHRAIN(code = "BH", index = 14),
    BANGLADESH(code = "BD", index = 15),
    BARBADOS(code = "BB", index = 16),
    BELARUS(code = "BY", index = 17),
    BELGIUM(code = "BE", index = 18),
    BELIZE(code = "BZ", index = 19),
    BENIN(code = "BJ", index = 20),
    BHUTAN(code = "BT", index = 21),
    BOLIVIA(code = "BO", index = 22),
    BOSNIA_AND_HERZEGOVINA(code = "BA", index = 23),
    BOTSWANA(code = "BW", index = 24),
    BOUVET_ISLAND(code = "BV", index = 25),
    BRAZIL(code = "BR", index = 26),
    BRUNEI_DARUSSALAM(code = "BN", index = 27),
    BULGARIA(code = "BG", index = 28),
    BURKINA_FASO(code = "BF", index = 29),
    BURUNDI(code = "BI", index = 30),
    CAMBODIA(code = "KH", index = 31),
    CAMEROON(code = "CM", index = 32),
    CANADA(code = "CA", index = 33),
    CAPE_VERDE(code = "CV", index = 34),
    CENTRAL_AFRICAN_REPUBLIC(code = "CF", index = 35),
    CHAD(code = "TD", index = 36),
    CHILE(code = "CL", index = 37),
    CHINA(code = "CN", index = 38),
    COLOMBIA(code = "CO", index = 39),
    COMOROS(code = "KM", index = 40),
    CONGO(code = "CG", index = 41),
    COSTA_RICA(code = "CR", index = 42),
    CROATIA(code = "HR", index = 43),
    CUBA(code = "CU", index = 44),
    CURA_AO(code = "CW", index = 45),
    CYPRUS(code = "CY", index = 46),
    CZECH_REPUBLIC(code = "CZ", index = 47),
    DR_CONGO(code = "CD", index = 48),
    DENMARK(code = "DK", index = 49),
    DJIBOUTI(code = "DJ", index = 50),
    DOMINICA(code = "DM", index = 51),
    DOMINICAN_REPUBLIC(code = "DO", index = 52),
    ECUADOR(code = "EC", index = 53),
    EGYPT(code = "EG", index = 54),
    EL_SALVADOR(code = "SV", index = 55),
    EQUATORIAL_GUINEA(code = "GQ", index = 56),
    ERITREA(code = "ER", index = 57),
    ESTONIA(code = "EE", index = 58),
    ESWATINI(code = "SZ", index = 59),
    ETHIOPIA(code = "ET", index = 60),
    FIJI(code = "FJ", index = 61),
    FINLAND(code = "FI", index = 62),
    FRANCE(code = "FR", index = 63),
    GABON(code = "GA", index = 64),
    GAMBIA(code = "GM", index = 65),
    GEORGIA(code = "GE", index = 66),
    GERMANY(code = "DE", index = 67),
    GHANA(code = "GH", index = 68),
    GREECE(code = "GR", index = 69),
    GRENADA(code = "GD", index = 70),
    GUATEMALA(code = "GT", index = 71),
    GUINEA(code = "GN", index = 72),
    GUINEA_BISSAU(code = "GW", index = 73),
    GUYANA(code = "GY", index = 74),
    HAITI(code = "HT", index = 75),
    HOLY_SEE(code = "VA", index = 76),
    HONDURAS(code = "HN", index = 77),
    HONG_KONG(code = "HK", index = 78),
    HUNGARY(code = "HU", index = 79),
    ICELAND(code = "IS", index = 80),
    INDIA(code = "IN", index = 81),
    INDONESIA(code = "ID", index = 82),
    IRAN(code = "IR", index = 83),
    IRAQ(code = "IQ", index = 84),
    IRELAND(code = "IE", index = 85),
    ISRAEL(code = "IL", index = 86),
    ITALY(code = "IT", index = 87),
    IVORY_COAST(code = "CI", index = 88),
    JAMAICA(code = "JM", index = 89),
    JAPAN(code = "JP", index = 90),
    JORDAN(code = "JO", index = 91),
    KAZAKHSTAN(code = "KZ", index = 92),
    KENYA(code = "KE", index = 93),
    KIRIBATI(code = "KI", index = 94),
    KUWAIT(code = "KW", index = 95),
    KYRGYZSTAN(code = "KG", index = 96),
    LAOS(code = "LA", index = 97),
    LATVIA(code = "LV", index = 98),
    LEBANON(code = "LB", index = 99),
    LESOTHO(code = "LS", index = 100),
    LIBERIA(code = "LR", index = 101),
    LIBYA(code = "LY", index = 102),
    LIECHTENSTEIN(code = "LI", index = 103),
    LITHUANIA(code = "LT", index = 104),
    LUXEMBOURG(code = "LU", index = 105),
    MADAGASCAR(code = "MG", index = 106),
    MALAWI(code = "MW", index = 107),
    MALAYSIA(code = "MY", index = 108),
    MALDIVES(code = "MV", index = 109),
    MALI(code = "ML", index = 110),
    MALTA(code = "MT", index = 111),
    MARSHALL_ISLANDS(code = "MH", index = 112),
    MAURITANIA(code = "MR", index = 113),
    MAURITIUS(code = "MU", index = 114),
    MEXICO(code = "MX", index = 115),
    MICRONESIA(code = "FM", index = 116),
    MOLDOVA(code = "MD", index = 117),
    MONACO(code = "MC", index = 118),
    MONGOLIA(code = "MN", index = 119),
    MONTENEGRO(code = "ME", index = 120),
    MOROCCO(code = "MA", index = 121),
    MOZAMBIQUE(code = "MZ", index = 122),
    MYANMAR(code = "MM", index = 123),
    NAMIBIA(code = "NA", index = 124),
    NAURU(code = "NR", index = 125),
    NEPAL(code = "NP", index = 126),
    NETHERLANDS(code = "NL", index = 127),
    NEW_ZEALAND(code = "NZ", index = 128),
    NICARAGUA(code = "NI", index = 129),
    NIGER(code = "NE", index = 130),
    NIGERIA(code = "NG", index = 131),
    NORTH_KOREA(code = "KP", index = 132),
    NORTH_MACEDONIA(code = "MK", index = 133),
    NORWAY(code = "NO", index = 134),
    OMAN(code = "OM", index = 135),
    PAKISTAN(code = "PK", index = 136),
    PALAU(code = "PW", index = 137),
    PALESTINE(code = "PS", index = 138),
    PANAMA(code = "PA", index = 139),
    PAPUA_NEW_GUINEA(code = "PG", index = 140),
    PARAGUAY(code = "PY", index = 141),
    PERU(code = "PE", index = 142),
    PHILIPPINES(code = "PH", index = 143),
    POLAND(code = "PL", index = 144),
    PORTUGAL(code = "PT", index = 145),
    QATAR(code = "QA", index = 146),
    ROMANIA(code = "RO", index = 147),
    RUSSIAN_FEDERATION(code = "RU", index = 148),
    RWANDA(code = "RW", index = 149),
    SAINT_LUCIA(code = "LC", index = 150),
    SAINT_VICENT_AND_THE_GRENADINES(code = "VC", index = 151),
    SAMOA(code = "WS", index = 152),
    SAN_MARINO(code = "SM", index = 153),
    SAO_TOME_AND_PRINCIPE(code = "ST", index = 154),
    SAUDI_ARABIA(code = "SA", index = 155),
    SENEGAL(code = "SN", index = 156),
    SERBIA(code = "RS", index = 157),
    SEYCHELLES(code = "SC", index = 158),
    SIERRA_LEONE(code = "SL", index = 159),
    SINGAPORE(code = "SG", index = 160),
    SINT_MAARTEN(code = "SX", index = 161),
    SLOVAKIA(code = "SK", index = 162),
    SLOVENIA(code = "SI", index = 163),
    SOLOMON_ISLANDS(code = "SB", index = 164),
    SOMALIA(code = "SO", index = 165),
    SOUTH_AFRICA(code = "ZA", index = 166),
    SOUTH_KOREA(code = "KR", index = 167),
    SOUTH_SUDAN(code = "SS", index = 168),
    SPAIN(code = "ES", index = 169),
    SRI_LANKA(code = "LK", index = 170),
    SUDAN(code = "SD", index = 171),
    SURINAME(code = "SR", index = 172),
    SWEDEN(code = "SE", index = 173),
    SWITZERLAND(code = "CH", index = 174),
    SYRIAN_ARAB_REPUBLIC(code = "SY", index = 175),
    TAJIKISTAN(code = "TJ", index = 176),
    TANZANIA(code = "TZ", index = 177),
    THAILAND(code = "TH", index = 178),
    TIMOR_LESTE(code = "TL", index = 179),
    TOGO(code = "TG", index = 180),
    TONGA(code = "TO", index = 181),
    TRINIDAD_AND_TOBAGO(code = "TT", index = 182),
    TUNISIA(code = "TN", index = 183),
    TURKEY(code = "TR", index = 184),
    TURKMENISTAN(code = "TM", index = 185),
    TUVALU(code = "TV", index = 186),
    UGANDA(code = "UG", index = 187),
    UKRAINE(code = "UA", index = 188),
    UNITED_ARAB_EMIRATES(code = "AE", index = 189),
    UNITED_KINGDOM(code = "GB", index = 190),
    UNITED_STATES_OF_AMERICA(code = "US", index = 191),
    URUGUAY(code = "UY", index = 192),
    UZBEKISTAN(code = "UZ", index = 193),
    VANUATU(code = "VU", index = 194),
    VENEZUELA(code = "VE", index = 195),
    VIETNAM(code = "VN", index = 196),
    // VIRGIN_ISLANDS(countryCode = "", index = -1), // Ambiguous (could be British VI-VG or US VI-VI)
    YEMEN(code = "YE", index = 198),
    ZAMBIA(code = "ZM", index = 199),
    ZIMBABWE(code = "ZW", index = 200);

    companion object {
        fun getIndex(code: String): Int? = entries.find { it.code == code }?.index
    }
}

/**
 * @param countryCode capitalized country code as defined in the ISO 3166-1 alpha 2 standard
 */
@Composable
fun Flag(countryCode: String) {
    val spriteIndex = Country.getIndex(countryCode)
    if (spriteIndex == null) {
        // draw emoji
    } else {
        // draw sprite
    }
}
